#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

$console = new \Symfony\Component\Console\Application('Code Generator');
$console->add(new \MPScholten\RequestParser\Foundation\Command\GenerateParser());

$console->run();
